In [124]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC
import pandas as pd

In [112]:
RANDOM_STATE = 5

In [113]:
germplasm_hw_tr = pd.read_pickle('Dataset/hw_encoded_tr.pkl')
germplasm_hw_test = pd.read_pickle('Dataset/hw_encoded_test.pkl')
germplasm_hw_val = pd.read_pickle('Dataset/hw_encoded_val.pkl')

In [ ]:
germplasm_sm_tr = pd.read_pickle('Dataset/sm_encoded_tr.pkl')
germplasm_sm_test = pd.read_pickle('Dataset/sm_encoded_test.pkl')
germplasm_sm_val = pd.read_pickle('Dataset/sm_encoded_val.pkl')

tr_fhb = pd.read_pickle('Dataset/tr_fhb.pkl')
test_fhb = pd.read_pickle('Dataset/test_fhb.pkl')
vali_fhb = pd.read_pickle('Dataset/vali_fhb.pkl')

# Random Forest

classifier = RandomForestClassifier(random_state=RANDOM_STATE)
classifier.fit(germplasm_hw_tr.to_numpy(), tr_fhb.to_numpy())

In [116]:
predicted = classifier.predict(germplasm_hw_test.to_numpy())

In [117]:
print('Classification report for Hardy Weinberg Equilibrium Features')
report = classification_report(test_fhb.to_numpy(), predicted)
print(report)
print()
conf_mat = confusion_matrix(test_fhb.to_numpy(), predicted)
print('Confusion matrix')
print(conf_mat)

Classification report for Hardy Weinberg Equilibrium Features
              precision    recall  f1-score   support

           1       0.67      0.33      0.44         6
           2       0.69      0.78      0.73        23
           3       0.36      0.36      0.36        11

    accuracy                           0.60        40
   macro avg       0.57      0.49      0.51        40
weighted avg       0.60      0.60      0.59        40


Confusion matrix
[[ 2  2  2]
 [ 0 18  5]
 [ 1  6  4]]


In [119]:
classifier = RandomForestClassifier(random_state=RANDOM_STATE)
classifier.fit(germplasm_sm_tr.to_numpy(), tr_fhb.to_numpy())

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=5, verbose=0,
                       warm_start=False)

In [120]:
predicted = classifier.predict(germplasm_sm_test.to_numpy())

In [121]:
print('Classification report for -1, 0, 1 Features')
report = classification_report(test_fhb.to_numpy(), predicted)
print(report)
print()
conf_mat = confusion_matrix(test_fhb.to_numpy(), predicted)
print('Confusion matrix')
print(conf_mat)

Classification report for -1, 0, 1 Features
              precision    recall  f1-score   support

           1       0.50      0.17      0.25         6
           2       0.70      0.83      0.76        23
           3       0.55      0.55      0.55        11

    accuracy                           0.65        40
   macro avg       0.58      0.51      0.52        40
weighted avg       0.63      0.65      0.62        40


Confusion matrix
[[ 1  4  1]
 [ 0 19  4]
 [ 1  4  6]]


In [ ]:
# SVM

In [125]:
classifier = SVC(random_state=RANDOM_STATE)
classifier.fit(germplasm_hw_tr.to_numpy(), tr_fhb.to_numpy())

/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=5,
    shrinking=True, tol=0.001, verbose=False)

In [126]:
predicted = classifier.predict(germplasm_hw_test.to_numpy())

In [127]:
print('Classification report for Hardy Weinberg Equilibrium Features')
report = classification_report(test_fhb.to_numpy(), predicted)
print(report)
print()
conf_mat = confusion_matrix(test_fhb.to_numpy(), predicted)
print('Confusion matrix')
print(conf_mat)

Classification report for Hardy Weinberg Equilibrium Features
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         6
           2       0.57      1.00      0.73        23
           3       0.00      0.00      0.00        11

    accuracy                           0.57        40
   macro avg       0.19      0.33      0.24        40
weighted avg       0.33      0.57      0.42        40


Confusion matrix
[[ 0  6  0]
 [ 0 23  0]
 [ 0 11  0]]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [128]:
classifier = SVC(random_state=RANDOM_STATE)
classifier.fit(germplasm_sm_tr.to_numpy(), tr_fhb.to_numpy())

/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=5,
    shrinking=True, tol=0.001, verbose=False)

In [129]:
predicted = classifier.predict(germplasm_hw_test.to_numpy())

In [130]:
print('Classification report for Hardy Weinberg Equilibrium Features')
report = classification_report(test_fhb.to_numpy(), predicted)
print(report)
print()
conf_mat = confusion_matrix(test_fhb.to_numpy(), predicted)
print('Confusion matrix')
print(conf_mat)

Classification report for Hardy Weinberg Equilibrium Features
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         6
           2       0.00      0.00      0.00        23
           3       0.28      1.00      0.43        11

    accuracy                           0.28        40
   macro avg       0.09      0.33      0.14        40
weighted avg       0.08      0.28      0.12        40


Confusion matrix
[[ 0  0  6]
 [ 0  0 23]
 [ 0  0 11]]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
